services:
  # Init to mount volumes
  init:
    image: wordpress:latest
    entrypoint: ["/bin/sh", "/init.sh"]
    volumes:
      - wp_app:/wordpress-content
      - ./wp_app:/wp_app
      - ./init.sh:/init.sh
    networks:
      - dokploy-network
    restart: on-failure

  wordpress:
    image: wordpress:latest
    networks:
      - dokploy-network
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: "${DB_USER}"
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
      WORDPRESS_DB_NAME: "${DB_NAME}"
      PHP_UPLOAD_MAX_FILESIZE: 64M
      PHP_POST_MAX_SIZE: 64M
      PHP_MAX_EXECUTION_TIME: 300
    volumes:
      - wp_app:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    depends_on:
      - init
      - db
    links:
      - db

  db:
    image: mysql:5.7.34
    networks:
      - dokploy-network
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wp_app:
  db_data:

networks:
  dokploy-network:
