version: "3.8"
services:
  # Init to mount volumes
  init:
    image: busybox
    command: ["/bin/sh", "/init.sh"]
    volumes:
      - wp_app:/var/www/html
      - ./wp_app:/wp_app
      - ./init.sh:/init.sh
    networks:
      - dokploy-network
    restart: on-failure

  wordpress:
    image: wordpress:latest
    networks:
      - dokploy-network
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: "${DB_USER}"
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
      WORDPRESS_DB_NAME: "${DB_NAME}"
    volumes:
    #   - "../files/wp_app/custom-theme:/var/www/html/wp-content/themes/custom-theme"
      - wp_app:/var/www/html
    depends_on:
      - init
      - db
    links:
      - db

  db:
    image: mysql:5.7.34
    networks:
      - dokploy-network
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wp_app:
  db_data:
