services:
  wordpress:
    image: wordpress:latest
    networks:
      - dokploy-network
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: "${DB_USER}"
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
      WORDPRESS_DB_NAME: "${DB_NAME}"
    volumes:
      - wp_content:/var/www/html/wp-content
      - ./wp_app:/wp_app
    entrypoint: ["/bin/sh", "-c", "cp -r /wp_app/* /var/www/html/ && exec docker-entrypoint.sh apache2-foreground"]
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:5.7.34
    networks:
      - dokploy-network
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wp_content:
  db_data:
